version: '3.4'

services: 
  naming-server:
    image: naming-server:0.0.1-SNAPSHOT
    ports:
      - 8762:8761
    networks:
      - erudio-network
  zipkin:
    image: openzipkin/zipkin:2.23.2
    ports:
      - 9412:9411
    networks:
      - erudio-network
networks:
  erudio-network:
    driver: bridge
      